### ISSUE TITLE
Preppy keeps spinning when an error is thrown

### ISSUE THREAD

**Issue by abrsil-WittGruppe** [sebastian-software/preppy#1]
When an error is thrown during the build, preppy doesn't show the error stacktrace and keeps spinning indefinitely.

I have to send SIGINT for the error to become visible:

![preppy](https://user-images.githubusercontent.com/40799940/48365513-7023f180-e6ab-11e8-9d4b-a5ddd573f328.gif)

## System Info

Don't know if its a shell problem, maybe this helps...

```sh
$ uname -a
MINGW64_NT-10.0 LAPTOP-40LVQP8D 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys

$ ps -p "$$"
      PID    PPID    PGID     WINPID   TTY         UID    STIME COMMAND
    25240       1   25240      25240  cons2     197609 10:37:30 /usr/bin/bash
```

**Comment by swernerx** [comment]
Fixed with v6.5.0. Thanks for reporting.
