### ISSUE TITLE
Support TypeScript declarationMap

### ISSUE THREAD

**Issue by n4bb12** [sebastian-software/preppy#2]
When generating TS types with the `declarationMap` option, additional `.d.ts.map` files are generated.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#new---declarationmap

Code editors can then take you to the `.ts` source instead of `.d.ts`.
This makes dependencies navigable just like regular source code in your project.

You can see this in action e.g. with the appllo projects that let you jump to the implementation.
https://github.com/apollographql/apollo-server/blob/master/tsconfig.base.json#L10

If you are open to supporting this option, I would attempt a PR.

**Comment by swernerx** [comment]
Sounds good. Please try out to make a PR.
